### ISSUE TITLE
Properly negotiate DHCP (IP change) so that shop stays open

### ISSUE THREAD

**Issue by fspc** [fspc/Yellow-Bike-Database#86]
When YBDB is on a network where static ip is not assigned, and the ip changes, the shop closes. Either an option to turn off checks for IP, or a way to verify the connecting computer is on the same subnet would resolve this issue.

That should be easy, just add an option to check for a subnet, eg. 192.168.8.*, using a regexp.

**Comment by fspc** [comment]
When YBDB is on a network where static ip is not assigned, and the ip changes, the shop closes. Either an option to turn off checks for IP, or a way to verify the connecting computer is on the same subnet would resolve this issue.

**Comment by Mayberrydeputy1** [comment]
Remove me from ur email list now Jonathan or I will be pressing charges for cyber harassment

**Comment by fspc** [comment]
When the ip changed the first shop become the later shop, and the new shop became the earlier shop. Probably, not necessary to fix if above approach works. However, the key is finding the real ip being used since it is the public ip address.

One solution would be to provide an option to turn off this feature, since its real intent is to separate shops or activities that are operating in different locations, and that feature is not used that often.

The other solution would be to provide an option to allow a regexp. In this real example a Class B Network is involved so anyone in *.* would be able to interact with the live shop (after logging in) if a regexp was used for that part. On the other hand, other networks wouldn't be able to access the interface. 

FIRST OPENED SHOP
mysql> SELECT ip_address FROM shops WHERE  shop_id=24; 
| ip_address   |
| *.*.1.2 |

SECOND OPENED SHOP
mysql> SELECT ip_address FROM shops WHERE  shop_id=23; 
| ip_address    |
| *.*.3.4 |

Both options could be provided, not ideal, but at least preventing the shop from inadvertently closing when a device (gateway) changes when it has a DHCP relationship to an external network.

A more sophisticated solution would be to limit the amount of devices that can connect to the regexp network or the application by keeping track of cookies or sessions. But then again, probably more than is really necessary.

The important function is current_shop_by_ip(), and the associated files it it running tests in.

**Comment by fspc** [comment]
After careful thought, the best solution would be to provide a DHCP option. When turned on, the current_shop_by_ip() function will change the recorded IP if DHCP in the database if the devices IP has changed.
